# Site settings
title: Almeida's resume
description: Paulo de Almeida's resume
favicon: /assets/img/avatar.jpg
pdficon: /assets/img/pdf-icon.png
baseurl: 
url: http://paulodealmeida.github.io
rss_url: /pages/atom.xml
google_analytics: UA-74208838-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Paulo de Almeida
  title: PHP Developer, CSM, CSD, CSPO
  address: Bahia, Brazil
  email: paulodealmeida@gmail.com
  link: http://paulodealmeida.github.io
  weibo:
  github: paulodealmeida
  linkedin: paulodealmeida00
#  twitter:
  wordpress: paulodealmeida
  gavatar: /assets/img/avatar.jpg
  stackoverflow:
  download_resume: https://drive.google.com/open?id=0B-8O4-REqyMsR3hSTEd6M1Vhd0k
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Soledade Tecnologia
      location: Bahia, Brazil
      title: Scrum Master and PHP developer
      started: 2015
      duration: (12/2015 - 07/2017)
      description: Development of dashboards, sales analysis system to Ricardo Eletro, and internal products using Laravel , Oracle and MySQL. Team guidance with Scrum knowledge, applying agile techniques to improve fast delivery. There we delivered an easy start project and improvements in Ubuntu script for a rapid environment configuration.
    
    - work2:
      company: Simetria Tecnologia
      location: Bahia, Brazil
      title: Team leader, scrum master and PHP developer
      started: 2014
      duration: (11/2014 – 12/2015)
      description: Team guidance and development of internal products using Laravel and MySQL.
    
    - work3:
      company: MW8 Soluções
      location: Bahia, Brazil
      title: Ruby developer
      started: 2014
      duration: (03/2014 – 11/2014)
      description: Development of internal products using Ruby on Rails and MySQL.

    - work4:
      company: Olaria
      location: Bahia, Brazil
      title: PHP developer
      started: 2013
      duration: (04/2013 – 03/2014)
      description: Development of internal products using PHP and MySQL.

    - work5:
      company: IMAP - Instituto Municipal de Administração Pública
      location: Bahia, Brazil
      title: PHP developer
      started: 2012
      duration: (08/2012 – 04/2013)
      description: Development of internal products using PHP and MySQL.

    - work6:
      company: NNSolutions
      location: Bahia, Brazil
      title: PHP developer
      started: 2011
      duration: (09/2011 – 08/2012)
      description: Development of internal products using CakePHP and MySQL.
  
  educationHistory:
    - education1:
      organization: União Metropolitana de Educação e Cultura, Bahia, Brazil
      location: Bahia, Brazil
      degree: MBA
      major: Project Management
      started: 2013
      duration: (2013 - 2015)
      description: 

    - education1:
      organization: União Metropolitana de Educação e Cultura, Bahia, Brazil
      location: Bahia, Brazil
      degree: Bachelor
      major: Information System
      started: 2009
      duration: (2009 - 2013)
      description: 

  languages:
    - language1:
      name: Portuguese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional

  programmingSkills:
    - skill1:
      name: PHP
      percentage: 90%
    - skill2:
      name: Ruby
      percentage: 50%
    - skill3:
      name: Python
      percentage: 50%
    - skill4:
      name: JavaScript
      percentage: 40%

  otherSkills:
    - skill1:
      name: Scrum
      percentage: 100%
    - skill2:
      name: Linux
      percentage: 90%
    - skill3:
      name: AWS
      percentage: 60%
