version: "3"

services:

    gh-pages:
        image: starefossen/github-pages
        container_name: paulodealmeida.github.io
        volumes:
            - ".:/usr/src/app"
        ports:
            - "4000:4000"
